include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments
    - sort_pub_dependencies
    - avoid_classes_with_only_static_members

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    sort_pub_dependencies: false
    avoid_classes_with_only_static_members: false
    avoid_multiple_declarations_per_line: false
    use_full_hex_values_for_flutter_colors: false
