environment_config:
  class: Env # class name for generated Dart file

  fields: # set of fields for command
    WEATHER_API_KEY:

    WEATHER_API_BASE_URL:

    GOOGLE_PLACES_KEY:

    BING_MAPS_BACKUP_API_KEY:

    BING_MAPS_BASE_URL:

    MIX_PANEL_TOKEN:

    ANDROID_TEST_AD_ID:

    REMOVE_ADS_PRODUCT_KEY:

    SENTRY_PATH:

    WEATHER_SERVICE_ID:

    WEATHER_KIT_KEY_ID:

    APPLE_TEAM_ID:

    iOsAdFreeProductId:

    androidAdFreeProductId:

    ANDROID_PROD_AD_ID:

    IOS_PROD_AD_ID:

    IOS_TEST_AD_ID:

    WEATHER_KIT_P8:
      
    IMAGE_CDN_URL:
      
    epicSkiesApiToken:
