environment_config:
  class: Env # class name for generated Dart file

  fields: # set of fields for command
    WEATHER_API_KEY:
      config_field: true

    WEATHER_API_BASE_URL:
      config_field: true

    GOOGLE_PLACES_KEY:
      config_field: true

    BING_MAPS_BACKUP_API_KEY:
      config_field: true

    BING_MAPS_BASE_URL:
      config_field: true

    MIX_PANEL_TOKEN:
      config_field: true

    ANDROID_TEST_AD_ID:
      config_field: true

    REMOVE_ADS_PRODUCT_KEY:
      config_field: true

    SENTRY_PATH:
      config_field: true
