name: epic_skies
description: Epic Weather App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.2+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  black_cat_lib:
    git: https://github.com/BlackCatDev-IO/black_cat_dev_library
  charcode: ^1.2.0
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  dio: ^4.0.3
  equatable: ^2.0.3
  firebase_analytics: ^8.3.4
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  geocoding: ^2.0.0
  get: ^4.3.8
  google_fonts: ^2.0.0
  hexcolor: ^2.0.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+3
  internet_connection_checker: ^0.0.1
  intl: ^0.17.0
  iphone_has_notch: ^1.0.0
  json_serializable: ^6.0.0
  lat_lng_to_timezone: ^0.2.0
  location: ^4.3.0
  meta: ^1.7.0
  nil: ^1.1.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  sentry_flutter: ^6.0.1
  sizer: ^2.0.13
  timezone: ^0.8.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  vibration: ^1.7.4-nullsafety.0

dependency_overrides: null
dev_dependencies:
  flutter_native_splash: ^1.1.7+1
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.16

flutter_native_splash:
  background_image: "assets/images/earth_from_space_with_logo.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/icons/vclouds_icons/
    - assets/icons/sun_time_icons/
    - assets/icons/precip_icons/
