name: epic_skies
description: Epic Weather App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.9+23

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  black_cat_lib:
    git: https://github.com/BlackCatDev-IO/black_cat_dev_library
  charcode: ^1.2.0
  cupertino_icons: ^1.0.2
  dart_date: ^1.1.0
  dio: ^4.0.6
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flat_buffers: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.1
  flutter_email_sender: ^5.1.0
  flutter_keyboard_visibility: ^5.4.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  hexcolor: ^2.0.5
  hydrated_bloc: ^9.0.0
  image_picker: ^0.8.4+3
  in_app_purchase: ^3.0.8
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  iphone_has_notch: ^1.0.0
  lat_lng_to_timezone: ^0.2.0
  location: ^4.4.0
  mixpanel_flutter: ^2.0.0
  nil: ^1.1.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.5
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.2
  scrollable_positioned_list: ^0.3.5
  sentry_flutter: ^6.18.2
  sizer: ^2.0.15
  timezone: ^0.8.0
  url_launcher: ^6.0.9
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.1.7
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  lint: ^1.5.3
  meta: ^1.7.0
  mocktail: ^0.3.0

flutter_native_splash:
  background_image: "assets/images/earth_from_space_with_logo.png"

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/icons/vclouds_icons/
    - assets/icons/sun_time_icons/
    - assets/icons/precip_icons/
    - .env
